#!/bin/bash

set -o errexit -o nounset -o pipefail

function prepend_path {
    if [[ $1 != /* ]]; then
        echo 'error: $HOME must be absolute' >&2
        return 1
    fi
    if [[ $1 == *:* ]]; then
        echo 'error: $HOME cannot contain a colon' >&2
        return 1
    fi
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH=$1${PATH:+:$PATH}
    esac
}

if grep -Fq VOLTA_HOME ~/.bashrc; then
    echo 'already installed' >&2
    #exit 1
fi

rm -rf ~/.local/share/volta

env='
# Volta
export VOLTA_HOME=$XDG_DATA_HOME/volta
export VOLTA_FEATURE_PNPM=1
prepend_path "$VOLTA_HOME/bin"'

eval "$env"
echo "$env" >> ~/.bashrc

if grep -Fq VOLTA_HOME ~/.bashrc; then
    exit 1
fi

curl -s https://get.volta.sh/ | bash

volta install node@latest
volta install pnpm@latest

for f in "$VOLTA_HOME"/bin/{npm,npx,yarn}; do
    [[ -L $f ]] && rm -f -- "$f"
done
rmdir -- "$VOLTA_HOME"/tools/{image,inventory}/{npm,yarn}
